# Generated by Django 4.2.4 on 2023-08-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=255)),
                ('Purchase', models.CharField(max_length=10)),
                ('Quantity', models.CharField(max_length=10)),
                ('Sale', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
