# Generated by Django 4.2.4 on 2023-08-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_created_date_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Note',
            field=models.TextField(),
        ),
    ]
